export const jobs = [
  {
    id: 1,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6c/Facebook_Logo_2023.png",
    CompanyName: "Facebook",
    position: "Product Designer",
    location: "New York, NY",
    salary: "3k",
    monthly: true,
    fullTime: true,
    dateOfPost: "2",
    description: "We are looking for a senior Product designer for our team",
    applied: "1000",
  },
  {
    id: 2,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/ef/Youtube_logo.png",
    CompanyName: "Youtube",
    position: "Web Developer",
    location: "Los Angeles, California",
    salary: "120k",
    monthly: false,
    fullTime: true,
    dateOfPost: "5",
    description: "We are looking for a senior Web Developer for our team",
    applied: "200",
  },
  {
    id: 3,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Paypal_2014_logo.png",
    CompanyName: "PayPal",
    position: "Product Designer",
    location: "New York, NY",
    salary: "3k",
    monthly: true,
    fullTime: true,
    dateOfPost: "2021-07-20",
    description: "We are looking for a senior Product designer for our team",
    applied: "1000",
  },
  {
    id: 4,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/de/Amazon_icon.png",
    CompanyName: "Amazon",
    position: "Product Designer",
    location: "New York, NY",
    salary: "3k",
    monthly: true,
    fullTime: true,
    dateOfPost: "2021-07-20",
    description: "We are looking for a senior Product designer for our team",
    applied: "1000",
  },
  {
    id: 5,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    CompanyName: "Microsoft",
    position: "Product Designer",
    location: "New York, NY",
    salary: "3k",
    monthly: true,
    fullTime: true,
    dateOfPost: "2021-07-20",
    description:
      "As a Product Designer, you will play a pivotal role in shaping the user experience and visual aesthetics of our products. You will collaborate closely with cross-functional teams, including product managers, engineers, and other stakeholders, to transform ideas and concepts into innovative and user-friendly designs. The ideal candidate possesses a passion for user-centered design, a keen eye for detail, and the ability to balance creativity with practicality As a Product Designer, you will play a pivotal role in shaping the user experience and visual aesthetics of our products. You will collaborate closely with cross-functional teams, including product managers, engineers, and other stakeholders, to transform ideas and concepts into innovative and user-friendly designs. The ideal candidate possesses a passion for user-centered design, a keen eye for detail, and the ability to balance creativity with practicalityAs a Product Designer, you will play a pivotal role in shaping the user experience and visual aesthetics of our products. You will collaborate closely with cross-functional teams, including product managers, engineers, and other stakeholders, to transform ideas and concepts into innovative and user-friendly designs. The ideal candidate possesses a passion for user-centered design, a keen eye for detail, and the ability to balance creativity with practicality As a Product Designer, you will play a pivotal role in shaping the user experience and visual aesthetics of our products. You will collaborate closely with cross-functional teams, including product managers, engineers, and other stakeholders, to transform ideas and concepts into innovative and user-friendly designs. The ideal candidate possesses a passion for user-centered design, a keen eye for detail, and the ability to balance creativity with practicality",
    applied: "1000",
  },
  {
    id: 6,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    CompanyName: "Apple",
    position: "Product Designer",
    location: "New York, NY",
    salary: "3k",
    monthly: true,
    fullTime: true,
    dateOfPost: "2021-07-20",
    description: "We are looking for a senior Product designer for our team",
    applied: "1000",
  },
];
